"""initial schema

Revision ID: 5dda2a04d29b
Revises: 
Create Date: 2026-05-27 14:19:15.067360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dda2a04d29b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('association_admins',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('work_id')
    )
    op.create_table('first_aid_contents',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('emergency_category', sa.String(), nullable=False),
    sa.Column('publication_status', sa.String(), nullable=False),
    sa.Column('author_vet_id', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_vet_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('pet_owners',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('veterinarians',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('specialisation', sa.String(), nullable=True),
    sa.Column('available_slots', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('timeslot', sa.String(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('pet_owner_id', sa.String(), nullable=False),
    sa.Column('vet_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.user_id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarians.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('guides',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['first_aid_contents.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pet_owners.user_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('quizzes',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['first_aid_contents.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('vet_advice_chats',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('pet_owner_id', sa.String(), nullable=False),
    sa.Column('vet_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.user_id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarians.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('videos',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['first_aid_contents.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['vet_advice_chats.chat_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.content_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('quiz_results',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('pet_owner_id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.user_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.content_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('quiz_results')
    op.drop_table('questions')
    op.drop_table('messages')
    op.drop_table('videos')
    op.drop_table('vet_advice_chats')
    op.drop_table('quizzes')
    op.drop_table('pets')
    op.drop_table('guides')
    op.drop_table('bookings')
    op.drop_table('veterinarians')
    op.drop_table('pet_owners')
    op.drop_table('first_aid_contents')
    op.drop_table('association_admins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
