"""add assigned vet id

Revision ID: fc39be3c2e8e
Revises: 5dda2a04d29b
Create Date: 2026-05-28 12:14:26.894824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc39be3c2e8e'
down_revision: Union[str, None] = '5dda2a04d29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('first_aid_contents', sa.Column('assigned_vet_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'first_aid_contents', 'users', ['assigned_vet_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'first_aid_contents', type_='foreignkey')
    op.drop_column('first_aid_contents', 'assigned_vet_id')
    # ### end Alembic commands ###
